name: Run conftest-unittests.sh

on:
  pull_request:
    branches: [ main ]

jobs:
  docker:
    name: Check docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Docker file code in the root directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if dockerimage build is working
        run: docker build -f ./Dockerfile .

  node-docker:
    runs-on: ubuntu-latest
    container:
      image: "./Dockerfile"
    steps:
         - name: Log the node version
           run: |
             skopeo inspect docker://quay.io/cvpops/test-index:v4.10
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conftest
        uses: redhat-cop/github-actions/confbatstest@master
        with:
          tests: tests/conftest-unittests.sh
          policies: '[]' # An empty array is provided as the policies are already cloned via source.
